# Generated by Django 5.2.7 on 2025-10-28 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_paciente', models.CharField(blank=True, max_length=15, null=True)),
                ('token_hash', models.CharField(max_length=128)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('OK', 'Acceso exitoso'), ('FAIL', 'Token inválido o expirado'), ('EXPIRED', 'Token expirado')], default='OK', max_length=20)),
                ('fecha_acceso', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Log de Acceso',
                'verbose_name_plural': 'Logs de Acceso',
                'db_table': 'visor_log_acceso',
                'ordering': ['-fecha_acceso'],
            },
        ),
        migrations.CreateModel(
            name='LogVisualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_paciente', models.CharField(max_length=15)),
                ('token_hash', models.CharField(max_length=128)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('documento_id', models.CharField(max_length=50)),
                ('fecha_visualizacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('accion', models.CharField(default='VISUALIZACION_PDF', max_length=30)),
            ],
            options={
                'verbose_name': 'Log de Visualización',
                'verbose_name_plural': 'Logs de Visualización',
                'db_table': 'visor_log_visualizacion',
                'ordering': ['-fecha_visualizacion'],
            },
        ),
    ]
